added custom functions

diff --git a/unix-like/zsh/functions b/unix-like/zsh/functions
--- a/unix-like/zsh/functions
+++ b/unix-like/zsh/functions
@@ -8,3 +8,23 @@ function mkcd() {
 function fdiff() {
     diff -u -t $1 $2 | diff-so-fancy
 }
+
+# shorter wrapper for `git` or `git status`
+function g() {
+    if [[ $# -gt 0 ]]; then
+        git "$@"
+    else
+        git status
+    fi
+}
+
+# check if command exists
+function exists() {
+    if ! [ -x "$(command -v $1)" ]; then
+        echo "Failure: $1 not found"
+        return 1
+    else
+        echo "Success: $(command -v $1)"
+        return 0
+    fi
+}
